---
title: "CherAnalysis"
output:
  html_document:
    code_folding: hide
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(modeest)
library(broom)
library(broom.mixed)
library(reshape2)
#library(gglasso)
library(glmnet)
library(lme4)
library(lmerTest)
library(sjPlot)
library(pscl)
library(readr)

#library(magrittr)
## Graphics
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(ggExtra)
library(ggsci)
library(scales)
library(viridis)
library(cowplot)

## tables
library(kableExtra)
library(xtable)

# Date functions
library(anytime)
library(lubridate)

```


# Load

Load all subjects

```{r}
bdata <- NULL
#data <- tibble()
```

```{r}
for (folder in dir("subject_data/")[grep("fnca", dir("subject_data/"))]) {
  partial <- read_csv(paste("subject_data", 
                            folder,
                            "subject.csv", sep="/"),
                      show_col_types = FALSE)
  partial$Subject <- folder
  if (is.null(bdata)) {
    bdata <- partial
  } else {
    #bdata <- full_join(bdata, partial) 
    bdata <- rbind(bdata, partial) 
  }
}

```


Load the model assignments

```{r}
assignments <- read_csv("LL_proc_decl2_new.csv", show_col_types = FALSE)
```

Merge the two, to make sure we have the same data

```{r}
full <- full_join(bdata, assignments, by="HCPID")
full <- full %>% filter(!is.na(BlockType), !is.na(PreviousFeedback))
```


# Group Differences in Response Switch

```{r}

adata_feedback <- full %>%
  group_by(HCPID, PreviousFeedback, BlockType) %>%
  summarise(ResponseSwitch = mean(ResponseSwitch),
            RT = mean(RT),
            Model=mlv(best.model),
            deltaLL = mean(diff.LL))
```

And now, let's visualize
```{r}
ggplot(adata_feedback, aes(x=PreviousFeedback, y=ResponseSwitch, fill=Model, col=Model)) +
  facet_wrap(~BlockType) +
  stat_summary(geom="point", fun.data="mean_se", alpha=0.6) +
  stat_summary(geom="errorbar", fun.data = "mean_se", width=0.1) +
  stat_summary(geom="line", aes(group=Model), fun.data="mean_se") +
  scale_color_d3() +
  theme_minimal()
```

# Group Differences in Persistance

Now, let's look at the data by block:

```{r}
adata_block <- full %>%
  filter(!is.na(BlockType)) %>%
  filter(!is.na(PreviousFeedback)) %>%
  group_by(HCPID, BlockType) %>%
  summarise(Persistance = mean(ConsecSameResp),
            MaxPersistance = max(ConsecSameResp),
            RT = mean(RT),
            Model=mlv(best.model),
            deltaLL = mean(diff.LL))


ggplot(adata_block, aes(x=Model, y=MaxPersistance, fill=Model, group=Model)) +
  facet_wrap(~BlockType) +
  stat_summary(geom="bar", position = "dodge") +
  stat_summary(geom="errorbar", position="dodge", width=0.1) +
  scale_fill_d3() +
  theme_minimal()
```

To analyze this, we will use generalized linear model with a Poisson distribution:

```{r}

mod1 <- glm(MaxPersistance ~ BlockType* Model ,  family="poisson", weights=abs(adata_block$deltaLL), data=adata_block)

mod1 %>%
  tidy() %>%
  kable() %>%
  kable_styling(bootstrap_options=c("striped", "hover"))

tab_model(mod1)
```